description: "Evaluate answer relevance"

providers:
  - openai:gpt-4o-mini
  - anthropic:messages:claude-sonnet-4-20250514
  - google:gemini-2.5-flash

prompts:
  - "Explain in simplest terms how to reset my Google password"
  - "Does enthnicity determine the size of kidney?"

tests:
  - assert:
    - type: answer-relevance
      threshold: 0.75
