# promptfooconfig.yaml
description: "csv prompt demo"
providers:
  - openai:gpt-4o                                 # OpenAI model ID
  - anthropic:messages:claude-sonnet-4-20250514   # Claude Sonnet model ID

prompts:
  - |
    You're a helpful assistant.
    Answer the following question clearly and concisely:
    {{question}}


#CSV with single assertion per test case
tests: file://tests/TestCase03_singleAssertion.csv